-- MySQL Script generated by MySQL Workbench
-- Mon Jan  7 12:50:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game` (
  `GAME_ID` BIGINT(20) NULL,
  `PURCHASING_VARIATION` TINYINT NOT NULL DEFAULT 0,
  `SELLING_VARIATION` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`GAME_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`schedule_demand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule_demand` (
  `UNITS` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `MOVEMENT` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UNITS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`player` (
  `PLAYER_ID` BIGINT(20) NOT NULL,
  `CALL_SIGN` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`PLAYER_ID`),
  UNIQUE INDEX `IDX_PLAYERS1` (`PLAYER_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`game_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_player` (
  `GAME_PLAYER_ID` BIGINT(20) NOT NULL,
  `GAME_ID` BIGINT(20) NOT NULL,
  `PLAYER_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`GAME_ID`, `PLAYER_ID`, `GAME_PLAYER_ID`),
  INDEX `fk_game_player_player1_idx` (`PLAYER_ID` ASC),
  CONSTRAINT `FK_GAME_PLAYERS`
    FOREIGN KEY (`GAME_ID`)
    REFERENCES `mydb`.`game` (`GAME_ID`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_game_player_player1`
    FOREIGN KEY (`PLAYER_ID`)
    REFERENCES `mydb`.`player` (`PLAYER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`game_player_turn_offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_player_turn_offer` (
  `GAME_ID` BIGINT(20) NOT NULL,
  `PLAYER_ID` BIGINT(20) NOT NULL,
  `TURN_ID` TINYINT NOT NULL,
  PRIMARY KEY (`GAME_ID`, `PLAYER_ID`, `TURN_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`game_player_turn_purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_player_turn_purchase` (
  `GAME_ID` BIGINT(20) NOT NULL,
  `PLAYER_ID` BIGINT(20) NOT NULL,
  `TURN_ID` TINYINT NOT NULL,
  PRIMARY KEY (`GAME_ID`, `PLAYER_ID`, `TURN_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`game_player_turn_sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_player_turn_sale` (
  `GAME_ID` BIGINT(20) NOT NULL,
  `PLAYER_ID` BIGINT(20) NOT NULL,
  `TURN_ID` TINYINT NOT NULL,
  PRIMARY KEY (`GAME_ID`, `PLAYER_ID`, `TURN_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `PRODUCT_CODE` CHAR(1) NOT NULL,
  `DISPLAY_PRIORITY` INT NOT NULL,
  PRIMARY KEY (`PRODUCT_CODE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`material` (
  `MATERIAL_CODE` VARCHAR(6) NOT NULL,
  `DISPLAY_PRIORITY` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`MATERIAL_CODE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product_material` (
  `PRODUCT_CODE` CHAR(1) NOT NULL,
  `MATERIAL_CODE` VARCHAR(6) NOT NULL,
  `AMOUNT` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`PRODUCT_CODE`, `MATERIAL_CODE`),
  INDEX `fk_product_material_material1_idx` (`MATERIAL_CODE` ASC),
  CONSTRAINT `FK_GAME_PRODUCTS_MATERIALS_2`
    FOREIGN KEY (`PRODUCT_CODE`)
    REFERENCES `mydb`.`product` (`PRODUCT_CODE`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_product_material_material1`
    FOREIGN KEY (`MATERIAL_CODE`)
    REFERENCES `mydb`.`material` (`MATERIAL_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`size_limits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`size_limits` (
  `GAME_SIZE` SMALLINT(6) NOT NULL,
  `STARTING_AMOUNT` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `ORDER_LIMITS` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`GAME_SIZE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`schedule_supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`schedule_supply` (
  `UNITS` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `MOVEMENT` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UNITS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`turn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turn` (
  `TURN_ID` TINYINT NOT NULL,
  `TURN_CODE` CHAR(3) NOT NULL,
  PRIMARY KEY (`TURN_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`game_turn_material_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_turn_material_price` (
  `GAME_ID` BIGINT(20) NOT NULL,
  `TURN_ID` TINYINT NOT NULL,
  `MATERIAL_CODE` VARCHAR(6) NOT NULL,
  `PRICE` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`GAME_ID`, `TURN_ID`, `MATERIAL_CODE`),
  INDEX `fk_game_turn_material_price_material1_idx` (`MATERIAL_CODE` ASC),
  INDEX `fk_game_turn_material_price_turn1_idx` (`TURN_ID` ASC),
  CONSTRAINT `fk_game_turn_material_price_material1`
    FOREIGN KEY (`MATERIAL_CODE`)
    REFERENCES `mydb`.`material` (`MATERIAL_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_turn_material_price_game1`
    FOREIGN KEY (`GAME_ID`)
    REFERENCES `mydb`.`game` (`GAME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_turn_material_price_turn1`
    FOREIGN KEY (`TURN_ID`)
    REFERENCES `mydb`.`turn` (`TURN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`game_turn_product_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game_turn_product_price` (
  `GAME_ID` BIGINT(20) NOT NULL,
  `TURN_ID` TINYINT NOT NULL,
  `PRODUCT_CODE` CHAR(1) NOT NULL,
  `PRICE` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`GAME_ID`, `TURN_ID`, `PRODUCT_CODE`),
  INDEX `game_turn_product_price_idx` (`PRODUCT_CODE` ASC),
  INDEX `fk_game_turn_product_price_turn1_idx` (`TURN_ID` ASC),
  CONSTRAINT `game_turn_product_price`
    FOREIGN KEY (`PRODUCT_CODE`)
    REFERENCES `mydb`.`product` (`PRODUCT_CODE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_turn_product_price_turn1`
    FOREIGN KEY (`TURN_ID`)
    REFERENCES `mydb`.`turn` (`TURN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_turn_product_price_game1`
    FOREIGN KEY (`GAME_ID`)
    REFERENCES `mydb`.`game` (`GAME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`game`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`game` (`GAME_ID`, `PURCHASING_VARIATION`, `SELLING_VARIATION`) VALUES (1, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`schedule_demand`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (0, -10);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (1, -9);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (2, -8);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (3, -7);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (4, -6);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (5, -5);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (6, -4);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (7, -3);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (8, -2);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (9, -1);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (10, 0);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (11, 1);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (12, 2);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (13, 3);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (14, 4);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (15, 5);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (16, 6);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (17, 7);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (18, 8);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (19, 9);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (20, 10);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (21, 11);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (22, 12);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (23, 13);
INSERT INTO `mydb`.`schedule_demand` (`UNITS`, `MOVEMENT`) VALUES (24, 14);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`player`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`player` (`PLAYER_ID`, `CALL_SIGN`) VALUES (1, 'Bubbajdf');
INSERT INTO `mydb`.`player` (`PLAYER_ID`, `CALL_SIGN`) VALUES (2, 'Justdoro');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`game_player`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`game_player` (`GAME_PLAYER_ID`, `GAME_ID`, `PLAYER_ID`) VALUES (1, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`product`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`product` (`PRODUCT_CODE`, `DISPLAY_PRIORITY`) VALUES ('A', 0);
INSERT INTO `mydb`.`product` (`PRODUCT_CODE`, `DISPLAY_PRIORITY`) VALUES ('B', 1);
INSERT INTO `mydb`.`product` (`PRODUCT_CODE`, `DISPLAY_PRIORITY`) VALUES ('C', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`material`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`material` (`MATERIAL_CODE`, `DISPLAY_PRIORITY`) VALUES ('X-FINE', 0);
INSERT INTO `mydb`.`material` (`MATERIAL_CODE`, `DISPLAY_PRIORITY`) VALUES ('FINE', 1);
INSERT INTO `mydb`.`material` (`MATERIAL_CODE`, `DISPLAY_PRIORITY`) VALUES ('STD', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`schedule_supply`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (0, 11);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (1, 9);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (2, 7);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (3, 5);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (4, 3);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (5, 1);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (6, -1);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (7, -3);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (8, -5);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (9, -7);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (10, -9);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (11, -11);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (12, -13);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (13, -15);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (14, -17);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (15, -19);
INSERT INTO `mydb`.`schedule_supply` (`UNITS`, `MOVEMENT`) VALUES (16, -21);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`turn`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (1, 'JAN');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (2, 'FEB');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (3, 'MAR');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (4, 'APR');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (5, 'MAY');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (6, 'JUN');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (7, 'JUL');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (8, 'AUG');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (9, 'SEP');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (10, 'OCT');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (11, 'NOV');
INSERT INTO `mydb`.`turn` (`TURN_ID`, `TURN_CODE`) VALUES (12, 'DEC');

COMMIT;

