
CREATE TABLE `games` (
  `GAME_ID` bigint(20) AUTO_INCREMENT,
  `TURN_PHASE_ID` smallint(6) NOT NULL,
  `PURCHASING_VARIATION` boolean not null default 0,
  `SELLING_VARIATION` boolean not null default 0,
  PRIMARY KEY (`GAME_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_demand_schedules` (
  `UNITS` int(11) unsigned NOT NULL DEFAULT '0',
  `MOVEMENT` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UNITS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_materials` (
  `MATERIAL_CODE` char(1) NOT NULL,
  PRIMARY KEY (`MATERIAL_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_players` (
  `GAME_ID` bigint(20) NOT NULL,
  `PLAYER_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`GAME_ID`,`PLAYER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_player_bids` (
  `GAME_ID` bigint(20) NOT NULL,
  `PLAYER_ID` bigint(20) NOT NULL,
  `TURN_ID` tinyint NOT NULL,
  PRIMARY KEY (`GAME_ID`,`PLAYER_ID`,`TURN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_player_offers` (
  `GAME_ID` bigint(20) NOT NULL,
  `PLAYER_ID` bigint(20) NOT NULL,
  `TURN_ID` tinyint NOT NULL,
  PRIMARY KEY (`GAME_ID`,`PLAYER_ID`,`TURN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_player_purchases` (
  `GAME_ID` bigint(20) NOT NULL,
  `PLAYER_ID` bigint(20) NOT NULL,
  `TURN_ID` tinyint NOT NULL,
  PRIMARY KEY (`GAME_ID`,`PLAYER_ID`,`TURN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_player_sales` (
  `GAME_ID` bigint(20) NOT NULL,
  `PLAYER_ID` bigint(20) NOT NULL,
  `TURN_ID` tinyint NOT NULL,
  PRIMARY KEY (`GAME_ID`,`PLAYER_ID`,`TURN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_products` (
  `PRODUCT_CODE` char(1) NOT NULL,
  PRIMARY KEY (`PRODUCT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_products_materials` (
  `PRODUCT_CODE` char(1) NOT NULL,
  `MATERIAL_CODE` char(1) NOT NULL,
  `ITEM_QUANTITY` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`PRODUCT_CODE`,`MATERIAL_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_size_limits` (
  `GAME_SIZE` smallint(6) NOT NULL,
  `STARTING_AMOUNT` int(11) unsigned NOT NULL DEFAULT '0',
  `ORDER_LIMITS` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`GAME_SIZE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_supply_schedules` (
  `UNITS` int(11) unsigned NOT NULL DEFAULT '0',
  `MOVEMENT` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`UNITS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_turn_material_prices` (
  `GAME_ID` bigint(20) NOT NULL,
  `TURN_ID` tinyint NOT NULL,
  `XFINE_PRICE` int(11) unsigned NOT NULL DEFAULT '0',
  `FINE_PRICE` int(11) unsigned NOT NULL DEFAULT '0',
  `STD_PRICE` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`GAME_ID`,`TURN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `game_turn_product_prices` (
  `GAME_ID` bigint(20) NOT NULL,
  `TURN_ID` tinyint NOT NULL,
  `A_PRICE` int(11) unsigned NOT NULL DEFAULT '0',
  `B_PRICE` int(11) unsigned NOT NULL DEFAULT '0',
  `C_PRICE` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`GAME_ID`,`TURN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `phases` (
  `PHASE_ID` smallint(6) NOT NULL,
  `PHASE_CODE` varchar(15) NOT NULL,
  PRIMARY KEY (`PHASE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `players` (
  `PLAYER_ID` bigint(20) NOT NULL,
  `CALL_SIGN` varchar(30) NOT NULL,
  PRIMARY KEY (`PLAYER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `turns` (
  `TURN_ID` tinyint NOT NULL,
  `TURN_CODE` char(3) NOT NULL,
  PRIMARY KEY (`TURN_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `turns_phases` (
  `TURN_PHASE_ID` smallint(6) NOT NULL,
  `TURN_ID` tinyint NOT NULL,
  `PHASE_ID` smallint(6) NOT NULL,
  PRIMARY KEY (`TURN_PHASE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/******************** CONSTRAINTS ********************/

ALTER TABLE GAME_PLAYERS ADD CONSTRAINT FK_GAME_PLAYERS
  FOREIGN KEY (GAME_ID) REFERENCES GAMES (GAME_ID) ON DELETE CASCADE;
ALTER TABLE GAME_PRODUCTS_MATERIALS ADD CONSTRAINT FK_GAME_PRODUCTS_MATERIALS_1
  FOREIGN KEY (MATERIAL_CODE) REFERENCES GAME_MATERIALS (MATERIAL_CODE) ON DELETE CASCADE;
ALTER TABLE GAME_PRODUCTS_MATERIALS ADD CONSTRAINT FK_GAME_PRODUCTS_MATERIALS_2
  FOREIGN KEY (PRODUCT_CODE) REFERENCES GAME_PRODUCTS (PRODUCT_CODE) ON DELETE CASCADE;
CREATE UNIQUE INDEX IDX_PLAYERS1 ON PLAYERS (PLAYER_ID);
