<?php
require_once EXEC_DECISION_CLASSES . 'TallyCardUtils.php';
?>

<h1 align="center">Executive Decision Tally</h1>
<head>
<link rel="stylesheet" type="text/css" href="css\tally-card.css">
</head>
<body>
<div class="topgrid">
<table>
  <tr>
    <th class="color" colspan="19">ORDERS</th>
  </tr>
<!-- JAN THRU JUNE -->
<?php
TallyCardUtils::CreateJANJUNOrderHeaders();
?>
 <tr>
   <td>X-FINE</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
 </tr>
 <tr>
   <td>FINE</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
 </tr>
 <tr>
   <td>STD.</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
 </tr>
 <tr>
   <th></th>
<?php
TallyCardUtils::CreateBlankTotals();
?>
 </tr>
<!-- JULY THRU DEC -->
<?php
TallyCardUtils::CreateJULDECOrderHeaders();
?>
 <tr>
   <td>X-FINE</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
 </tr>
 <tr>
   <td>FINE</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
 </tr>
 <tr>
   <td>STD.</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
 </tr>
 <tr>
   <th></th>
<?php
TallyCardUtils::CreateBlankTotals();
?>
 </tr>
</table>
<!-- SALES -->
<table>
  <tr>
    <th class="color" colspan="19">SALES</th>
  </tr>
<!-- JAN THRU JUNE -->
<?php
TallyCardUtils::CreateJANJUNSalesHeaders();
?>
    <td>A</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
  </tr>
  <tr>
    <td>B</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
  </tr>
  <tr>
    <td>C</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
  </tr>
 <tr>
   <th></th>
<?php
TallyCardUtils::CreateBlankTotals();
?>
 </tr>
<!-- JULY THRU DEC -->
<?php
TallyCardUtils::CreateJULDECSalesHeaders();
?>
  <tr>
    <td>A</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
  </tr>
  <tr>
    <td>B</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
  </tr>
  <tr>
    <td>C</td>
<?php
TallyCardUtils::CreateBlankColumns();
?>
  </tr>
 <tr>
   <th></th>
<?php
TallyCardUtils::CreateBlankTotals();
?>
 </tr>
</table>
</body>
</div>
